//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionType {
            get {
                return ((string)(this["ConnectionType"]));
            }
            set {
                this["ConnectionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Configuration {
            get {
                return ((string)(this["Configuration"]));
            }
            set {
                this["Configuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IpAddress {
            get {
                return ((string)(this["IpAddress"]));
            }
            set {
                this["IpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubnetMask {
            get {
                return ((string)(this["SubnetMask"]));
            }
            set {
                this["SubnetMask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Ssid {
            get {
                return ((string)(this["Ssid"]));
            }
            set {
                this["Ssid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profile=\"(Default)\">L2")]
        public string SelectedVesselType {
            get {
                return ((string)(this["SelectedVesselType"]));
            }
            set {
                this["SelectedVesselType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan TotalWorkTime {
            get {
                return ((global::System.TimeSpan)(this["TotalWorkTime"]));
            }
            set {
                this["TotalWorkTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FoamSelectedMode {
            get {
                return ((string)(this["FoamSelectedMode"]));
            }
            set {
                this["FoamSelectedMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AntiFoamDoseTime {
            get {
                return ((int)(this["AntiFoamDoseTime"]));
            }
            set {
                this["AntiFoamDoseTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AntiFoamWaitTime {
            get {
                return ((int)(this["AntiFoamWaitTime"]));
            }
            set {
                this["AntiFoamWaitTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AntiFoamAlarmTime {
            get {
                return ((int)(this["AntiFoamAlarmTime"]));
            }
            set {
                this["AntiFoamAlarmTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LevelDoseTime {
            get {
                return ((int)(this["LevelDoseTime"]));
            }
            set {
                this["LevelDoseTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LevelWaitTime {
            get {
                return ((int)(this["LevelWaitTime"]));
            }
            set {
                this["LevelWaitTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LevelAlarmTime {
            get {
                return ((int)(this["LevelAlarmTime"]));
            }
            set {
                this["LevelAlarmTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string pO2SelectedCascade {
            get {
                return ((string)(this["pO2SelectedCascade"]));
            }
            set {
                this["pO2SelectedCascade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pO2StirrerRPM {
            get {
                return ((int)(this["pO2StirrerRPM"]));
            }
            set {
                this["pO2StirrerRPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pO2TotalFlowTotalFlow {
            get {
                return ((int)(this["pO2TotalFlowTotalFlow"]));
            }
            set {
                this["pO2TotalFlowTotalFlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pO2GasMixGasMix {
            get {
                return ((int)(this["pO2GasMixGasMix"]));
            }
            set {
                this["pO2GasMixGasMix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pO2StirrerTotalFlowRPM {
            get {
                return ((int)(this["pO2StirrerTotalFlowRPM"]));
            }
            set {
                this["pO2StirrerTotalFlowRPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pO2StirrerTotalFlowTotalFlow {
            get {
                return ((int)(this["pO2StirrerTotalFlowTotalFlow"]));
            }
            set {
                this["pO2StirrerTotalFlowTotalFlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pO2StirrerGasMixRPM {
            get {
                return ((int)(this["pO2StirrerGasMixRPM"]));
            }
            set {
                this["pO2StirrerGasMixRPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pO2StirrerGasMixGasMix {
            get {
                return ((int)(this["pO2StirrerGasMixGasMix"]));
            }
            set {
                this["pO2StirrerGasMixGasMix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pO2StirrerTotalFlowGasMixRPM {
            get {
                return ((int)(this["pO2StirrerTotalFlowGasMixRPM"]));
            }
            set {
                this["pO2StirrerTotalFlowGasMixRPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pO2StirrerTotalFlowGasMixTotalFlow {
            get {
                return ((int)(this["pO2StirrerTotalFlowGasMixTotalFlow"]));
            }
            set {
                this["pO2StirrerTotalFlowGasMixTotalFlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pO2StirrerTotalFlowGasMixGasMix {
            get {
                return ((int)(this["pO2StirrerTotalFlowGasMixGasMix"]));
            }
            set {
                this["pO2StirrerTotalFlowGasMixGasMix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pHBaseBase {
            get {
                return ((int)(this["pHBaseBase"]));
            }
            set {
                this["pHBaseBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pHAcidAcid {
            get {
                return ((int)(this["pHAcidAcid"]));
            }
            set {
                this["pHAcidAcid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pHBaseAcidBase {
            get {
                return ((int)(this["pHBaseAcidBase"]));
            }
            set {
                this["pHBaseAcidBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pHBaseAcidAcid {
            get {
                return ((int)(this["pHBaseAcidAcid"]));
            }
            set {
                this["pHBaseAcidAcid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string pHSelectedCascade {
            get {
                return ((string)(this["pHSelectedCascade"]));
            }
            set {
                this["pHSelectedCascade"] = value;
            }
        }
    }
}
