//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionType {
            get {
                return ((string)(this["ConnectionType"]));
            }
            set {
                this["ConnectionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Configuration {
            get {
                return ((string)(this["Configuration"]));
            }
            set {
                this["Configuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IpAddress {
            get {
                return ((string)(this["IpAddress"]));
            }
            set {
                this["IpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SubnetMask {
            get {
                return ((string)(this["SubnetMask"]));
            }
            set {
                this["SubnetMask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Ssid {
            get {
                return ((string)(this["Ssid"]));
            }
            set {
                this["Ssid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L2")]
        public string SelectedVesselType {
            get {
                return ((string)(this["SelectedVesselType"]));
            }
            set {
                this["SelectedVesselType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan TotalWorkTime {
            get {
                return ((global::System.TimeSpan)(this["TotalWorkTime"]));
            }
            set {
                this["TotalWorkTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string FoamSelectedMode {
            get {
                return ((string)(this["FoamSelectedMode"]));
            }
            set {
                this["FoamSelectedMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AntiFoamDoseTime {
            get {
                return ((double)(this["AntiFoamDoseTime"]));
            }
            set {
                this["AntiFoamDoseTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AntiFoamWaitTime {
            get {
                return ((double)(this["AntiFoamWaitTime"]));
            }
            set {
                this["AntiFoamWaitTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AntiFoamAlarmTime {
            get {
                return ((double)(this["AntiFoamAlarmTime"]));
            }
            set {
                this["AntiFoamAlarmTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LevelDoseTime {
            get {
                return ((double)(this["LevelDoseTime"]));
            }
            set {
                this["LevelDoseTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LevelWaitTime {
            get {
                return ((double)(this["LevelWaitTime"]));
            }
            set {
                this["LevelWaitTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LevelAlarmTime {
            get {
                return ((double)(this["LevelAlarmTime"]));
            }
            set {
                this["LevelAlarmTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string pO2SelectedCascade {
            get {
                return ((string)(this["pO2SelectedCascade"]));
            }
            set {
                this["pO2SelectedCascade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1400")]
        public double pO2StirrerRPM {
            get {
                return ((double)(this["pO2StirrerRPM"]));
            }
            set {
                this["pO2StirrerRPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public double pO2TotalFlowTotalFlow {
            get {
                return ((double)(this["pO2TotalFlowTotalFlow"]));
            }
            set {
                this["pO2TotalFlowTotalFlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double pO2GasMixGasMix {
            get {
                return ((double)(this["pO2GasMixGasMix"]));
            }
            set {
                this["pO2GasMixGasMix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1400")]
        public double pO2StirrerTotalFlowRPM {
            get {
                return ((double)(this["pO2StirrerTotalFlowRPM"]));
            }
            set {
                this["pO2StirrerTotalFlowRPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public double pO2StirrerTotalFlowTotalFlow {
            get {
                return ((double)(this["pO2StirrerTotalFlowTotalFlow"]));
            }
            set {
                this["pO2StirrerTotalFlowTotalFlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1400")]
        public double pO2StirrerGasMixRPM {
            get {
                return ((double)(this["pO2StirrerGasMixRPM"]));
            }
            set {
                this["pO2StirrerGasMixRPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double pO2StirrerGasMixGasMix {
            get {
                return ((double)(this["pO2StirrerGasMixGasMix"]));
            }
            set {
                this["pO2StirrerGasMixGasMix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1400")]
        public double pO2StirrerTotalFlowGasMixRPM {
            get {
                return ((double)(this["pO2StirrerTotalFlowGasMixRPM"]));
            }
            set {
                this["pO2StirrerTotalFlowGasMixRPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public double pO2StirrerTotalFlowGasMixTotalFlow {
            get {
                return ((double)(this["pO2StirrerTotalFlowGasMixTotalFlow"]));
            }
            set {
                this["pO2StirrerTotalFlowGasMixTotalFlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double pO2StirrerTotalFlowGasMixGasMix {
            get {
                return ((double)(this["pO2StirrerTotalFlowGasMixGasMix"]));
            }
            set {
                this["pO2StirrerTotalFlowGasMixGasMix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double pHBaseBase {
            get {
                return ((double)(this["pHBaseBase"]));
            }
            set {
                this["pHBaseBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double pHAcidAcid {
            get {
                return ((double)(this["pHAcidAcid"]));
            }
            set {
                this["pHAcidAcid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double pHBaseAcidBase {
            get {
                return ((double)(this["pHBaseAcidBase"]));
            }
            set {
                this["pHBaseAcidBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double pHBaseAcidAcid {
            get {
                return ((double)(this["pHBaseAcidAcid"]));
            }
            set {
                this["pHBaseAcidAcid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string pHSelectedCascade {
            get {
                return ((string)(this["pHSelectedCascade"]));
            }
            set {
                this["pHSelectedCascade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedpO2Cascade {
            get {
                return ((string)(this["LastSelectedpO2Cascade"]));
            }
            set {
                this["LastSelectedpO2Cascade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedpO2CascadeItem {
            get {
                return ((string)(this["LastSelectedpO2CascadeItem"]));
            }
            set {
                this["LastSelectedpO2CascadeItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double pO2P {
            get {
                return ((double)(this["pO2P"]));
            }
            set {
                this["pO2P"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double pO2I {
            get {
                return ((double)(this["pO2I"]));
            }
            set {
                this["pO2I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public double pO2ILimit {
            get {
                return ((double)(this["pO2ILimit"]));
            }
            set {
                this["pO2ILimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double pO2Deadband {
            get {
                return ((double)(this["pO2Deadband"]));
            }
            set {
                this["pO2Deadband"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double pO2Negfactor {
            get {
                return ((double)(this["pO2Negfactor"]));
            }
            set {
                this["pO2Negfactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double pO2EvalTime {
            get {
                return ((double)(this["pO2EvalTime"]));
            }
            set {
                this["pO2EvalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideStirrerBorder {
            get {
                return ((bool)(this["HideStirrerBorder"]));
            }
            set {
                this["HideStirrerBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideAirFlowBorder {
            get {
                return ((bool)(this["HideAirFlowBorder"]));
            }
            set {
                this["HideAirFlowBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedpHCascadeItem {
            get {
                return ((string)(this["LastSelectedpHCascadeItem"]));
            }
            set {
                this["LastSelectedpHCascadeItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double pHP {
            get {
                return ((double)(this["pHP"]));
            }
            set {
                this["pHP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public double pHI {
            get {
                return ((double)(this["pHI"]));
            }
            set {
                this["pHI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double pHILimit {
            get {
                return ((double)(this["pHILimit"]));
            }
            set {
                this["pHILimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double pHDeadband {
            get {
                return ((double)(this["pHDeadband"]));
            }
            set {
                this["pHDeadband"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double pHNegFactor {
            get {
                return ((double)(this["pHNegFactor"]));
            }
            set {
                this["pHNegFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double pHEvalTime {
            get {
                return ((double)(this["pHEvalTime"]));
            }
            set {
                this["pHEvalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Pump1TargetValue {
            get {
                return ((double)(this["Pump1TargetValue"]));
            }
            set {
                this["Pump1TargetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Pump2TargetValue {
            get {
                return ((double)(this["Pump2TargetValue"]));
            }
            set {
                this["Pump2TargetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Pump3TargetValue {
            get {
                return ((double)(this["Pump3TargetValue"]));
            }
            set {
                this["Pump3TargetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Pump4TargetValue {
            get {
                return ((double)(this["Pump4TargetValue"]));
            }
            set {
                this["Pump4TargetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Pump5TargetValue {
            get {
                return ((double)(this["Pump5TargetValue"]));
            }
            set {
                this["Pump5TargetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Pump6TargetValue {
            get {
                return ((double)(this["Pump6TargetValue"]));
            }
            set {
                this["Pump6TargetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Pump1FillValue {
            get {
                return ((double)(this["Pump1FillValue"]));
            }
            set {
                this["Pump1FillValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Pump2FillValue {
            get {
                return ((double)(this["Pump2FillValue"]));
            }
            set {
                this["Pump2FillValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Pump3FillValue {
            get {
                return ((double)(this["Pump3FillValue"]));
            }
            set {
                this["Pump3FillValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Pump4FillValue {
            get {
                return ((double)(this["Pump4FillValue"]));
            }
            set {
                this["Pump4FillValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Pump1EmptyValue {
            get {
                return ((double)(this["Pump1EmptyValue"]));
            }
            set {
                this["Pump1EmptyValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Pump2EmptyValue {
            get {
                return ((double)(this["Pump2EmptyValue"]));
            }
            set {
                this["Pump2EmptyValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Pump3EmptyValue {
            get {
                return ((double)(this["Pump3EmptyValue"]));
            }
            set {
                this["Pump3EmptyValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Pump4EmptyValue {
            get {
                return ((double)(this["Pump4EmptyValue"]));
            }
            set {
                this["Pump4EmptyValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FoamLevel {
            get {
                return ((int)(this["FoamLevel"]));
            }
            set {
                this["FoamLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RedoxP {
            get {
                return ((double)(this["RedoxP"]));
            }
            set {
                this["RedoxP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RedoxI {
            get {
                return ((double)(this["RedoxI"]));
            }
            set {
                this["RedoxI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RedoxILimit {
            get {
                return ((double)(this["RedoxILimit"]));
            }
            set {
                this["RedoxILimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RedoxDeadband {
            get {
                return ((double)(this["RedoxDeadband"]));
            }
            set {
                this["RedoxDeadband"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RedoxNegfactor {
            get {
                return ((double)(this["RedoxNegfactor"]));
            }
            set {
                this["RedoxNegfactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RedoxEvalTime {
            get {
                return ((double)(this["RedoxEvalTime"]));
            }
            set {
                this["RedoxEvalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedRedoxCascadeItem {
            get {
                return ((string)(this["LastSelectedRedoxCascadeItem"]));
            }
            set {
                this["LastSelectedRedoxCascadeItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RedoxSelectedCascade {
            get {
                return ((string)(this["RedoxSelectedCascade"]));
            }
            set {
                this["RedoxSelectedCascade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedRedoxCascade {
            get {
                return ((string)(this["LastSelectedRedoxCascade"]));
            }
            set {
                this["LastSelectedRedoxCascade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideGas2FlowBorder {
            get {
                return ((bool)(this["HideGas2FlowBorder"]));
            }
            set {
                this["HideGas2FlowBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RedoxGas2N2 {
            get {
                return ((double)(this["RedoxGas2N2"]));
            }
            set {
                this["RedoxGas2N2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RedoxAirFlowAir {
            get {
                return ((double)(this["RedoxAirFlowAir"]));
            }
            set {
                this["RedoxAirFlowAir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RedoxTotalFlowTotalFlow {
            get {
                return ((double)(this["RedoxTotalFlowTotalFlow"]));
            }
            set {
                this["RedoxTotalFlowTotalFlow"] = value;
            }
        }
    }
}
